# Generated by Django 3.1.7 on 2021-08-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='countries',
            new_name='hotels',
        ),
    ]
